### ISSUE TITLE
Reduxでアプリケーションの状態を管理する。

### ISSUE THREAD

**Issue by niceonionslice** [niceonionslice/react-sandbox#5]
# Rudexの構成
ReactというViewライブラリを利用してアプリケーションを作成してきたが、Rudexを利用することで登場人物が増えます。
- Store
- Reducer
- Action

Storeは、アプリケーションの状態(store)とロジックを保持している場所
Reducerは、Storeが保持している状態を変化させているための関数
Actionは、ユーザーから入力であったり、APIからの情報取得であったり、何らかの状態変化を引き起こす現象をさす。

**Comment by niceonionslice** [comment]
# Reduxをインストール

`yarn add -s redux`

実行してみたけど。。ERRになった。

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py\", line 16, in <module>
    sys.exit(gyp.script_main())
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 545, in script_main
    return main(sys.argv[1:])
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 538, in main
    return gyp_main(args)
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 795, in Write
    self.Pchify))
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py\", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py\", line 1265, in XcodeVersion
    version = re.match(r'(\\d\\.\\d\\.?\\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/bin/node\" \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64\" \"--python=/usr/bin/python\"
gyp ERR! cwd /Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/bin/node /Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node --module_name=fse --module_path=/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64 --python=/usr/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command \"/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/bin/node\" \"/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/bin/node /Users/kojiro.yamashiro/.anyenv/envs/nodenv/versions/8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node --module_name=fse --module_path=/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64 --python=/usr/bin/python' (1)"
```

**Comment by niceonionslice** [comment]
xcode-select: error: tool 'xcodebuild'で検索してこのサイトを確認。
https://qiita.com/macococo/items/41a1ea97ddd9f6974032

`xcode-select`はインストール済みでパスも通っていた。

**Comment by niceonionslice** [comment]
エラーの冒頭のメッセージ
```
warning ../package.json: No license field
warning Error running install script for optional dependency: "/Users/kojiro.yamashiro/Projects/private/react-sandbox/my-app2/node_modules/fsevents: Command failed.
```

**Comment by niceonionslice** [comment]
https://qiita.com/akameco/items/301aff5f30d673c6ab17
このサイトにあるように`yarn upgrade`するように言われたの実行。

結局とところ
`yarn add redux`で解決することができた。

**Comment by niceonionslice** [comment]
なんとかreduxを利用したstore管理の方法を整理することができた。
まずは、storeから整理する。

**Comment by niceonionslice** [comment]
# reduxでは状態を管理するためのstoreを作成するための関数（createStore）が用意されている。
crateStoreで状態を管理するための処理を定義する。

引数は２つあり、１つは現在のstateオブジェクトが渡されます。
もう一つはstateを更新するためのactionオブジェクトが渡されます。

**Comment by niceonionslice** [comment]
createStoreではreducerを自分でfunctionとして用意することにある。
例えば

```
function tasksReducer(state = initialState, action) {
  switch (action.type) {
    case 'ADD_TASK':
      return {
        ...state,
        // tasks: state.tasks.concat([action.task]) //← 教科書はこれですが、payloadオブジェクトの中を追加するので下に記述を変更
        tasks: state.tasks.concat([action.payload.task])
      };
    default:
      return state;
  }
};
```

**Comment by niceonionslice** [comment]
本の通りに初めても意味がわからないことが多い。
とりあえず、まとめると。

reduxを利用する時には

① 状態を管理するためのオブジェクトを用意する
② 状態を変更するためのreducerと呼ばれるfunctionを用意する。用意した後にcreateStoreで登録する。
③ Actionを定義する。
④ createStoreで作成されたstoreのdispatchで状態を変更する。
⑤ storeのsubscribeにstoreが変更になったタイミングで呼び出すfunctionを定義する。これがコールバック関数

**Comment by niceonionslice** [comment]
# 重要そうなところを写経 
handleChangeをsubscribeしているため、dispatchによって状態が変わったタイミングでhandleChangeが呼ばれる。dispatch前に最初、初期のStareとしてtasksには空の配列が格納されている。dispatch後にはコールバック関数としてhandleChangeが呼び出され、Stateが変化していることを確認することができます。

subscribeを実行すると戻り値としてunsubscribeが返却される。これを実行することでコールバックの呼び出しを解除することができます。

react-reduxというライブラリを利用するとsubscribeの仕組みを隠蔽しStoreの状態が変化した場合にはreactのviewを更新します。

**Comment by niceonionslice** [comment]
# reduxの本家のサンプルコード

↓ こんな感じで状態を管理する方法を定義して状態を変える方法はdispatchを利用しないという方法。デザインパターンを言ってもいいかもしれない。

```
import { createStore } from 'redux'

/**
 * This is a reducer, a pure function with (state, action) => state signature.
 * It describes how an action transforms the state into the next state.
 *
 * The shape of the state is up to you: it can be a primitive, an array, an object,
 * or even an Immutable.js data structure. The only important part is that you should
 * not mutate the state object, but return a new object if the state changes.
 *
 * In this example, we use a `switch` statement and strings, but you can use a helper that
 * follows a different convention (such as function maps) if it makes sense for your
 * project.
 */
function counter(state = 0, action) {
  switch (action.type) {
    case 'INCREMENT':
      return state + 1
    case 'DECREMENT':
      return state - 1
    default:
      return state
  }
}

// Create a Redux store holding the state of your app.
// Its API is { subscribe, dispatch, getState }.
let store = createStore(counter)

// You can use subscribe() to update the UI in response to state changes.
// Normally you'd use a view binding library (e.g. React Redux) rather than subscribe() directly.
// However it can also be handy to persist the current state in the localStorage.

store.subscribe(() => console.log(store.getState()))

// The only way to mutate the internal state is to dispatch an action.
// The actions can be serialized, logged or stored and later replayed.
store.dispatch({ type: 'INCREMENT' })
// 1
store.dispatch({ type: 'INCREMENT' })
// 2
store.dispatch({ type: 'DECREMENT' })
// 1
```
